### ISSUE TITLE
ENH: Always generate updated RDF, OWL, JSON-LD

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#197] opened 2014-12-12 12:58 UTC
This has been requested a number of times on the mailing list and on Twitter.

~~RDF and OWL could/should be added to a Makefile (or a comparable Python script).~~

RDF and/or OWL could also be generated on-demand by api.py, in addition to the schema transformations maintained by TopBraid.

It is unreasonable and wasteful to expect end-users to parse/scape and transform this RDFa, every time, themselves.

Source Code Links:
- https://github.com/rvguha/schemaorg/blob/master/app.yaml
- https://github.com/rvguha/schemaorg/blob/master/api.py
- https://github.com/rvguha/schemaorg/blob/master/run_tests.py
- https://github.com/rvguha/schemaorg/blob/master/tests/test_basics.py
- https://github.com/rvguha/schemaorg/blob/master/tests/test_graphs.py
### Schema.org ontology instances
- [x] RDFa: http://schema.org/docs/schema_org_rdfa.html

These are all out of date and incomplete:
- [ ] RDF:
- [ ] OWL: http://schema.org/docs/schemaorg.owl
  
   https://github.com/rvguha/schemaorg/commits/master/docs/schemaorg.owl
- [ ] JSON-LD: http://schema.org/docs/jsonldcontext.json

These are all out of date and incomplete:
- http://schema.rdfs.org/all.rdf
- http://schema.rdfs.org/all.nt
- http://schema.rdfs.org/all.ttl
- http://schema.rdfs.org/mappings.html

These are maintained (out of band) by TopBraid. They appear to be fairly regularly updated:
- [x] http://topbraid.org/schema/
- [x] http://topbraid.org/schema/schema.rdf
- [x] http://topbraid.org/schema/schema.ttl
- [x] http://topbraid.org/schema/schema-single-range.ttl

**Comment by danbri** [comment] 2015-01-21 11:46
Filing this in someday pile, will break out more specific issues where needed that are feasible near-term. We are unlikely to make an OWL version anytime soon, for example, whereas JSON-LD, maybe CSV, ... is more important.

**Comment by gkellogg** [comment] 2015-01-21 18:33
@danbri, now that you seem to have a Ruby environment installed, you might try installing the JSON-LD gem and running `rake schema_context` to get an example JSON-LD including the document and RDFSish vocabulary definition. We can, of course, tweak as you see fit. (Also, note that this is "D3" compatible output for your nice diagrams.

**Comment by westurner** [comment] 2015-01-22 00:29
Would it be easier to generate a JSON-LD context from
http://topbraid.org/schema/ ?

**Comment by danbri** [comment] 2015-01-22 08:07
The problem is not so much generating the JSON-LD context (which we'll do in pure python rather than complicate the tooling and publication workflow or using a non-schema.org version of schema.org) - but making sure it says the right things in the data. Afterwards we can make the JSON-LD representation fancier, or stick a fancy version alongside.

**Comment by westurner** [comment] 2015-01-22 14:43
So your plan is to just apply valid RDF / OWL semantics later?

Why? Why would you do that?

False dichotomy: "RDFS-ish" // valid OWL

* http://wrdrd.github.io/docs/consulting/knowledge-engineering.html#owl
* http://www.w3.org/TR/owl2-profiles/

**Comment by danbri** [comment] 2020-07-17 11:05
Closing as obsolete.

**Closed by danbri** 2020-07-17 11:05 UTC
Labels: site tools + python code

**Comment by westurner** [comment] 2020-07-17 11:50
What is this obsoleted by?

**Comment by westurner** [comment] 2020-07-17 11:56
Is https://schema.org/docs/schemaorg.owl current?

Are the schema extensions also available with the same transformations applied? Is the source of these transformations published?

Particularly health-lifesci; Protegé

**Comment by danbri** [comment] 2020-07-17 12:27
Schema.org is not defined in terms of OWL. The OWL representation you mention (and linked from /docs/developers.html) is experimental and in some ways (the conversion to rdfs:domain and rdfs:range) a misleading representation of Schema.org. But you can get versioned snapshots for recent releases, if OWL is your thing. The source of everything is in Github.

```#schemaorg/data/releases
master└─ $ ls -1v */*owl
3.9/schemaorg.owl
4.0/schemaorg.owl
5.0/schemaorg.owl
6.0/schemaorg.owl
7.0/schemaorg.owl
7.01/schemaorg.owl
7.02/schemaorg.owl
7.03/schemaorg.owl
7.04/schemaorg.owl
8.0/schemaorg.owl
9.0/schemaorg.owl```

On the OWL point, https://schema.org/docs/developers.html

> OWL
> As an experimental feature, an OWL definition file schemaorg.owl is available. It includes the core and all current extensions to the vocabulary.
> The structure of the file differs from the above vocabulary definition files, in that schema:domainIncludes and schema:rangeIncludes values are converted into rdfs:domain and rdfs:range values using owl:unionOf to capture the multiplicity of values. Included in the range values are the, implicit within the vocabulary, default values of Text, URL, and Role.
> This file has been made available to enable the representation of the vocabulary in some OWL-based modeling tools. The mapping into OWL is an approximation, and should not be considered an authoritative definition for Schema.org's terms; see datamodel page for details. As an experimental feature, there are no expectations as to its interpretation by any third party tools.
