### ISSUE TITLE
Different/wrong descriptions in current live version

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1232] opened 2016-06-28 12:46 UTC
(My first thought was that this results from the commit that reverted/removed many terms, but I’m not sure, so to err on the side of caution, I’m reporting this. It doesn’t seem to be a problem on http://webschemas.org/)

Several terms seem to have the wrong description on their own term page *or* in the table on a type page, but (for properties) not in both places (as far as I found).

#### Example: `serviceType` ####

On http://schema.org/Service it says for `serviceType`:

> Implementors and publishers are cautioned that terms in the pending extension may lack consensus and that terminology and definitions could still change significantly after community and steering group review. Consumers of schema.org data who encourage use of such terms are strongly encouraged to update implementations and documentation to track any evolving changes, and to share early implementation feedback with the wider community.

But on http://schema.org/serviceType it correctly says:

> The type of service being offered, e.g. veterans' benefits, emergency relief, etc.

#### Example: `specialOpeningHoursSpecification` ####

On http://schema.org/specialOpeningHoursSpecification it wrongly says:

> The place where the Organization was founded.

But on http://schema.org/Place is correctly says for `specialOpeningHoursSpecification`:

> The special opening hours of a certain place.  
> Use this to explicitly override general opening hours brought in scope by openingHoursSpecification or openingHours.

#### Example: `Product` ####

Wrong description for http://schema.org/Product

> A collection of datasets.

**Comment by unor** [comment] 2016-06-29 04:52
Another odd thing: http://schema.org/contactPoint is listed as extension in pending.

**Comment by danbri** [comment] 2016-06-30 16:05
@RichardWallis any thoughts?

**Comment by danbri** [comment] 2016-06-30 16:07
I don't see this text, 

"On http://schema.org/Service it says for serviceType:

Implementors and publishers are cautioned that terms in the pending extension may lack consensus and that terminology and definitions could still change significantly after community and steering group review. Consumers of schema.org data who encourage use of such terms are strongly encouraged to update implementations and documentation to track any evolving changes, and to share early implementation feedback with the wider community."

... anywhere in http://schema.org/Service

@unor would you mind making a screenshot (in a small zoomed-out font ideally) and/or upload a copy of the page to gist.github.com so we can make sure we're talking about the same thing?

**Comment by unor** [comment] 2016-06-30 16:31
Oh, now all three cases from the opening post are correct again. (I guess [the thing with `contactPoint`](https://github.com/schemaorg/schemaorg/issues/1232#issuecomment-229255892) is something unrelated.)

For me they showed the wrong text for at least two days, and I cleared the cache several times, and tried different browsers.

**Comment by Dataliberate** [comment] 2016-06-30 17:18
ContactPoint is referenced in the Pending Extension - as it should as there
are proposed (#1062 <https://github.com/schemaorg/schemaorg/issues/1062>)
domain/range changes.

However it is defined as being partOf http://pending.schema.org which it
isn’t.  That triple needs removing.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment] 2016-06-30 17:35
Ok I've tweaked the mention of contactPoint (not ContactPoint) in data/ext/pending/ see commit just pushed. Also updating sdo-makemake and webschemas sites.

**Comment by danbri** [comment] 2016-07-29 18:17
I believe we ought to close this as "can't reproduce", which isn't ideal, but hopefully at least indicates that it is rare. Let's keep watch for this kind of weirdness, and we can reopen this issue if we notice anything.

**Closed by danbri** 2016-07-29 18:17 UTC
