### ISSUE TITLE
Better wording for StructuredValue

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#394] opened 2015-03-24 22:29 UTC
The wording for http://schema.org/StructuredValue is no longer appropriate, since it refers to strings, while this type is now used as a supertype for all kinds of structured value entities.

**Comment by danbri** [comment] 2015-04-17 20:32
True, but duplicate of #109 - closing this in favour of the existing record.

**Closed by danbri** 2015-04-17 20:32 UTC
