### ISSUE TITLE
Vocabulary (or extension, community group etc.) for legal decisions and/or legislation

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#980] opened 2016-02-03 14:03 UTC
There are a few groups interested in schema.org-based ways of describing / annotating legal decision records, and/or official legislation. This is a placeholder to gather information on these efforts, which may be worth creating one or more W3C Community Groups for.

See also:
- https://lists.w3.org/Archives/Public/public-schemaorg/2015May/0027.html "vocabulary for legal decision (e.g., Supreme Court cases)" thread from @stuartrobinson
- http://doc.metalex.eu/ Dutch Regulations as Linked Data from  [Rinke Hoekstra](http://www.few.vu.nl/~hoekstra/), @RinkeHoekstra
- ... more?

See also several related (to some broad extent) issues:
- https://github.com/schemaorg/schemaorg/issues/452 - proposal for detail on legal forms of organizations
- https://github.com/schemaorg/schemaorg/issues/784 - Clarification / generalization of Attorney type as LegalService
- https://github.com/schemaorg/schemaorg/issues/969 - FIBO - finance oriented, also touches on legal entity types.
- #1156  - A proposal for an extension to describe legislation (added May 2016)

**Comment by akuckartz** [comment] 2016-02-04 19:36
To some extent this is a duplicate of #448

**Comment by danbri** [comment] 2016-02-04 19:44
Thanks @akuckartz - I'd missed that connection. There are a lot of angles to opengov efforts, including description of civic services, open datasets etc. which touch on existing efforts; the legislation / legal records aspect seems to be a subset.

**Comment by martenkoetsier** [comment] 2016-02-19 09:36
Would this also be an opportunity to add types for certification?

Many businesses advertise being certified by this/that organisation. E.g. an engineer working according to some ISO principles, a painter working according to environmental standards, etc. As a potential customer, I would be interested in a search for (local) businesses that are certified. Using schema.org types for these certificates may help here.

Some certification is mandatory for certain products/services by law in some jurisdictions, but there are also a lot of optional certificates. Therefore, I'm not sure this idea fits in your proposal, please tell me if it's better to start a separate topic about this.

**Comment by tfrancart** [comment] 2016-02-25 13:56
[ELI](http://www.eli.fr/en/) (European Legislation Identifier) is an initiative aimed at identifying and describing legislation at European level (directives) and domestic level (national legislation, and especially how they relate to European directives). The first version of a [metadata model](http://publications.europa.eu/mdr/eli/) was agreed to allow European Official Journal publishers to share legislation metadata by adding RDFa in their webpages.
The ELI taskforce is currently analysing the gap between the ELI ontology and schema.org, and will propose an extension (typically a subtype of schema:CreativeWork, and legislation-specific links like "cites", "consolidates", "transposes", "basedOn", etc.)

**Comment by tfrancart** [comment] 2016-05-11 10:49
A proposal for an extension to describe legislation has been submitted in #1156 .

**Comment by danbri** [comment] 2016-06-03 21:14
Thanks @tfrancart - I've added #1156 to the description at the top of this issue

**Closed** 2024-11-13 02:34 UTC
Labels: schema.org vocab, no-issue-activity

**Comment by tfrancart** [comment] 2024-11-14 07:49
@danbri we are sorry to see this issue set as "not planned" with respect to the proposal for the [Legislation](https://schema.org/Legislation) type as originally proposed in #1156.
Is this the result of a conscious decision or rather an automatic flag set automatically by a bot ?
