### ISSUE TITLE
Add Property "volume"

### ISSUE THREAD

**Issue by radusi** [schemaorg/schemaorg#738] opened 2015-08-16 07:26 UTC
"volume" property at least for products is as popular as weight, width, length, height. In EU in grocery eCommerce, is mandatory price specification / sales unit ( bottle ) and MU ( liter )

**Comment by mfhepp** [comment] 2015-08-16 08:01
will take care.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by vholland** [comment] 2015-08-17 13:14
This is a duplicate of issue #544. Can we continue the discussion there?

**Closed by vholland** 2015-08-17 13:14 UTC
