### ISSUE TITLE
Mark successorOf/predecessorOf as mutual inverses

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1142] opened 2016-05-03 15:14 UTC
- http://schema.org/successorOf
- http://schema.org/predecessorOf

This is vocabulary originally from GoodRelations, and pre-dates our ability to express inverseOf relationships (which means cross-links between the corresponding pages are missing).

**Comment by mfhepp** [comment] 2016-05-03 16:00
+1
This is also how it was defined in GoodRelations:
http://www.heppnetz.de/ontologies/goodrelations/v1.html#predecessorOf

**Comment by RichardWallis** [comment] 2016-10-26 12:30
Fixed by commit df0d380947fadf62dcfe29436c1c7c69844107c3

**Comment by RichardWallis** [comment] 2016-10-26 13:34
Ignore previous commit notice - caused by a typo in a not connected commit elsewhere.

~Richard

**Closed** 2024-11-08 02:34 UTC
Labels: schema.org vocab, status:work expected, type:cleanup + clarity, no-issue-activity
