### ISSUE TITLE
Remove Accommodation from all of the Offer-related schema and use MTEs instead

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1264] opened 2016-07-26 17:56 UTC
Pull request #1224 added Accommodation to some properties related to Offers (itemOffered, offers, typeOfGood).

Given schema.org has a stated preference for using Multiple Typed Entities, we should remove Accommodation from the domain/range of the above properties and rewrite the example to demonstrate how to specify something is both an Accommodation and a Product.

**Comment by danbri** [comment] 2016-07-26 18:09
http://schema.org/docs/datamodel.html has always said "We have a set of types, arranged in a multiple inheritance hierarchy where each type may be a sub class of multiple types.". 

In my view the time has come to re-emphasize this point e.g. by adding mention of it in the Conformance section of that page too. 

It is very reasonable to say that things can have multiple types, and that in any given situation diverse properties may be relevant/useful depending on the type(s) of the thing being described. 

We (i.e. schema.org) should not have to up-front anticipate all such combinations within schema.org's fixed definitions directly, either through the association of properties to types, or through baking in multiple supertypes as we've done with LocalBusiness (which has Place and Organization as supertypes). 

/cc @mfhepp @rvguha @chaals @shankarnat @scor @tmarshbing

**Comment by mfhepp** [comment] 2016-07-26 18:33
Well ...

1. I can live with that, but if all or most use-cases of Accommodation require it to be combined with Product, then we could as well make it a subtype of Product as in the initial proposal. Note that this does not conflict with the usage of some Accommodation subtypes in real estate offers; they will also have to be MTEs then. You might argue that a lot of the commodity-minded properties of Product are not really useful for Accommodations (like GTIN), but then expanding the domain and range of the three properties is cleaner than allowing all GTINs etc. on housing.

2. Before we go that route, all major sponsors should swear that their validation tools and production system will never ever discriminate MTEs, and in particular never mark MTEs as invalid markup.

**Comment by rvguha** [comment] 2016-07-26 19:13
Yes, absolutely. I could not agree more. It should be only in the very rare
case (like Local business) that we bake it in using multiple super types.

guha

**Comment by rvguha** [comment] 2016-07-26 19:15
See replies inline

On Tue, Jul 26, 2016 at 11:33 AM, Martin Hepp <notifications@github.com>
wrote:

> Well ...
>
>    1.
>
>    I can live with that, but if all or most use-cases of Accommodation
>    require it to be combined with Product, then we could as well make it a
>    subtype of Product as in the initial proposal. Note that this does not
>    conflict with the usage of some Accommodation subtypes in real estate
>    offers; they will also have to be MTEs then. You might argue that a lot of
>    the commodity-minded properties of Product are not really useful for
>    Accommodations (like GTIN), but then expanding the domain and range of the
>    three properties is cleaner than allowing all GTINs etc. on housing.
>
>
That would be short sighted. In reality, most accommodations are not
products and our ontology should reflect that, not just what some
particular use cases of today do.

**Comment by mfhepp** [comment] 2016-07-26 19:19
Guha:
The current design does not use multiple super-types. Instead, it includes Accommodation and its subtypes in the domain / range of offers, itemOffered etc.,

The alternatives under discussion are

a) leave it as in the last proposal (my favourite, because then Accommodation won't have GTIN codes)
b) recommend multi-types at the instance / markup level (Dan / Vicki's proposal) or
c) have two super-types at the class / type-level, i.e. multi-types at the class hierarchy level.

I understand your position regarding c), but I do not understand why b) should be more in line with your preferences than a).

Martin

**Comment by thadguidry** [comment] 2016-07-26 19:23
Agreed with @rvguha where we should try to lessen the burden of Developers...even if it makes us as stakeholders have to do a bit more modeling and schema grinding work.

"What would Jarno do ?" @jvandriel would pick b) recommend multi-types at the instance / markup level (Dan / Vicki's proposal)

**Comment by mfhepp** [comment] 2016-07-26 19:25
> On 26 Jul 2016, at 21:15, R.V.Guha <notifications@github.com> wrote:
> 
> On Tue, Jul 26, 2016 at 11:33 AM, Martin Hepp <notifications@github.com>
> wrote:
> 
> > Well ...
> >
> > 1.
> >
> > I can live with that, but if all or most use-cases of Accommodation
> > require it to be combined with Product, then we could as well make it a
> > subtype of Product as in the initial proposal. Note that this does not
> > conflict with the usage of some Accommodation subtypes in real estate
> > offers; they will also have to be MTEs then. You might argue that a lot of
> > the commodity-minded properties of Product are not really useful for
> > Accommodations (like GTIN), but then expanding the domain and range of the
> > three properties is cleaner than allowing all GTINs etc. on housing.
> >
> >
> That would be short sighted. In reality, most accommodations are not
> products and our ontology should reflect that, not just what some
> particular use cases of today do.

The root of the problem is that in GoodRelations, "Product" is a role that a "Thing" can have, i.e. being the object of an offer or transaction.

In schema.org, "Product" has a narrower meaning, something like "boxed commodity for sale or rental".

We could fix that by introducing a more abstract class like "TradeableObject" (not a serios name proposal).

Ok, I assume you will like this as much as an "Agent" type ;-)
> 
> 
> >
> > 1.
> >
> > Before we go that route, all major sponsors should swear that their
> > validation tools and production system will never ever discriminate MTEs,
> > and in particular never mark MTEs as invalid markup.
> >
> Are you serious? I hope you are not.

Well, kind of. While I understand the complex setting between schema.org and its sponsors business operations, it will be a bad design decision from the vocabulary part if we introduce new patterns that invalidate markup or irritate developers by throwing error messages.

And since MTEs have been a source of pain for developers for months if not years, I think this aspect needs to be taken serious.

If we cannot assume that MTEs are properly supported by Google, Bing, Yahoo, Yandex, then we can simply not make design decision in the vocabulary that ar built atop of MTEs.

Martin

**Comment by danbri** [comment] 2016-07-26 20:49
Nobody is going to be swearing about anything. As I say, my feeling is that MTEs deserve another push. If we conclude that this push has failed, we can add back in the workaround hacks. But I don't think this is something we should give up on, and more often than not the pain point will be around "Product" since we'll keep running into situations like Accommodation and Book where product properties are useful but it is awkward to handle those types as if they were simply specialized kinds of Product. 

Another important driver for this is that we have been moving towards having more schema.org extensions, both hosted via subdomains and external like http://gs1.org/voc/ . 

Even if schema.org could reasonably be expected to carefully police its own type hierarchy to avoid any need for multiple supertypes, this becomes increasingly less plausible as multiple partially-independent schemas come into play. While schema.org and our network of W3C community groups gives an environment where loose integration and collaboration can happen, it is much harder to get rigid agreement on mutual disjointness of classes from such diverse groups. Support for MTEs will allow reasonable-looking structured data to mix in diverse types without forcing slow, bureaucratic schema review across the entire ecosystem. It will benefit everyone, including large scale consumers.

**Comment by thadguidry** [comment] 2016-07-27 01:54
@danbri Good points...and I personally saw that benefit of reasonable looking structured data by mixing diverse types (even freelanced User created types like mine!)... in Freebase...that's how we rolled it back in the day. :)  Rest its soul.

**Comment by jvandriel** [comment] 2016-07-27 02:11
> _"What would Jarno do ?"_

In this particular case I'd prefer to see ew go for (b). Not because I think (a) is wrong in any form but I feel this is a great opportunity to finally start building a foundation for the use of MTEs in schema.org's examples.

Talking about whether or not the sponsors will update their side of things to accept the use of MTEs is a bit of a NULL discussion IMHO if we don't demonstrate the use of it on schema.org itself.

And even though I've been speaking my mind freely about the lack of support for MTEs by the sponsors, on different channels - for quite some, I do trust that if the use of MTEs grows (because schema.org demonstrates them) that the sponsors eventuelly will catch up.

(Would be awesome if I'd could stop pointing folks to the Structured Data Linter as opposed to the Structured Data Testing tool though - currently it feels a bit like I've got 'parrot' tattooed on my forehead)

**Comment by danbri** [comment] 2016-07-28 18:58
A quick recap of current state:

 * petsAllowed domainIncludes Accommodation 
 * offers domainIncludes Accommodation 
 * validThrough domainIncludes AccommodationFeature 
 * permittedUsage domainIncludes Accommodation 
 * hoursAvailable domainIncludes AccommodationFeature 
 * itemOffered rangeIncludes Accommodation 
 * typeOfGood rangeIncludes Accommodation 
 * feature rangeIncludes AccommodationFeature 
 * validFrom domainIncludes AccommodationFeature 
 * floorSize domainIncludes Accommodation 
 * feature domainIncludes Accommodation 

I've commited changes to datamodel.html that should clarify our use of MTEs, see http://webschemas.org/docs/datamodel.html#conformance

The candidates for moving to MTE are: itemOffered validThrough  typeOfGood and offers

**Comment by mfhepp** [comment] 2016-07-28 20:56
ok - in the version of the post that was shared by email, also validThrough was mentioned as an MTE candidate, which I would object to. The mechanism here is for indicating the availability times of a feature or service (like sauna).

**Comment by danbri** [comment] 2016-07-28 21:28
@mfhepp I mentioned validThrough because it showed up when I grepped for Accomodation, but before I excluded the AccomodationFeature rows. It was an error which I didn't catch before github sent the 1st draft of this comment out by email, sorry about that!

**Comment by danbri** [comment] 2016-07-29 15:10
I've done my best to reflect rough consensus from this discussion into the release candidate that I have just proposed for release, https://lists.w3.org/Archives/Public/public-schemaorg/2016Jul/0015.html

**Comment by danbri** [comment] 2016-07-29 15:21
Looks like I didn't commit the edit for 'offers' properly. Fixing that now, sorry!

**Comment by danbri** [comment] 2016-08-10 14:54
Done!

**Closed by danbri** 2016-08-10 14:54 UTC
Labels: schema.org vocab, type:exact proposal, type:small proposal
