### ISSUE TITLE
FOAF:HomePage as substitute for WebPage > HomePage?

### ISSUE THREAD

**Issue by EnnexMB** [schemaorg/schemaorg#2436] opened 2020-01-08 22:30 UTC
This issue is picking up from where the issue:

- [Add type: Thing > CreativeWork > WebPage > HomePage](https://github.com/schemaorg/schemaorg/issues/2062)

left off. But let's not continue the debate on whether to have a HomePage subtype of WebPage. I have a whole new question.

When @DanBri closed that issue, he said it was because "As far as I see, nobody in this thread is proposing to use actually HomePage or LandingPage type." I e-mailed him, saying that on the contrary, I opened that issue because I want to use the subtype “HomePage” on the home pages of my websites when I implement structured data in them. He replied that when he said "use" he meant it in the sense of building tools/services and products that extract and consume the markup. Okay, well that is not something I intend to do. And then he said:

> If all you want is an rdf vocabulary that has a representation of the notion of a homepage, you can use the foaf:homepage property

Hmm, that's interesting. It's also a little over my head because I had to look up [rdf vocabulary](https://en.wikipedia.org/wiki/RDF_Schema) and [foaf:homepage](https://udfr.org/docs/onto/foaf_homepage.html) and it's gonna take some reading to come up to speed.

So here are my new questions:

- If what I want is that when I implement structured data in my websites, to be able to designate their main pages as homepages, then does that mean that "all I want is an rdf vocabulary that has a representation of the notion of a homepage"?
- Do other people agree that `foaf:homepage` is how I can designate the main pages of my websites as homepages?
- If the answer to that question is yes, then why in 16 months of that thread did no one ever say that? Is there something I should have said more clearly to get that solution to be suggested?

**Comment by WeaverStever** [comment] 2020-01-09 08:51
We don't really deal with RDF here, so there is that.  

I took a look at the docs, and it appears that foaf is more aligned with the old vCards we used to attach to our emails.  The email applications knew how to read the attached data.

So you could use the example below to decorate your homePages, but it does not "declare" the page as a homePage, it tells the data consumer where the homePage is.

~~~~
<foaf:Person rdf:about="#danbri" xmlns:foaf="http://xmlns.com/foaf/0.1/">
  <foaf:name>Dan Brickley</foaf:name>
  <foaf:homepage rdf:resource="http://danbri.org/" />
  <foaf:openid rdf:resource="http://danbri.org/" />
  <foaf:img rdf:resource="/images/me.jpg" />
</foaf:Person>
~~~~
http://xmlns.com/foaf/spec/

So if you want to decorate your pages, and figure out how to consume the data (SPARQL) internally, foaf / rdf may work for you.

The example above does not generate any result on Google's Structured Data Testing Tool, so I would reckon that a JSON-LD query would yield nothing. 
************************
Question:

Since most every sub-type is covered why not make an internal rule that @type webPage is always a home page and use sub-types (or nothing) for the other pages? You could use the inLanguage property if you have a bunch of "homePages" in different languages.

**Comment by EnnexMB** [comment] 2020-01-09 10:24
@WeaverStever , if you are right, it sounds like FOAF would **_NOT_** provide the functionality for which I would implement structured data, which is not to "decorate" my pages, but to have them understood by the bots.

@DanBri , could you respond here and say whether that is correct?

> most every sub-type [of webpage] is covered

If the list of "More specific types" near the bottom of the [spec page for WebPage](https://schema.org/WebPage) is a complete list of defined subtypes, the eleven types in that list does not nearly cover all subtypes. It's just a list of some common types of webpages. There are many, many more (maybe an infinite, or at least uncountable, number), such as blog post, podcast, video, article, book, news report, etc., etc., etc., and let's not forget, also, homepage!

**Comment by WeaverStever** [comment] 2020-01-10 05:08
@EnnexMB 
You wrote:
> ...which is not to "decorate" my pages, but to have them understood by the bots.

In that case, I would suggest that you implement a breadcrumb approach to site(s) design.
https://schema.org/BreadcrumbList

This will help the Knowledge Graph "bots" understand the structure of your site(s). 

**********************

That said, homePage has a much broader meaning than just a subtype of webPage, I can't imagine why anyone would want dozens of homePages (subtype of webPage) under the same domain. I believe that this would be a completely incorrect implementation of the name.

Alternately, if we declare HomePage at the same level as WebSite, we would inform the Knowledge Graph that "this" Domain hosts many sudo-websites at the subdirectory level. AKA, there are additional website-like structures on this host. Structured-data that is specific to these sudo-website(s) is not necessarily about the parent domain etc.

Example WebSite:
(a WebSite could not also be a HomePage -- HOME is assumed to resolve to "/")
~~~
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "http://example.com/"
}
</script>
~~~

Example HomePage:
(a sudo-website where structured-data (etc) does not necessary pertain to the host (parent) domain. A HomePage should never resolve to "/".)
~~~
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "HomePage",
    "url": "http://example.com/sudo-website/",
    "folksonomy":[{
         "name": "@sudo-website",
          "url": "http://example.com/sudo-website/"
      },{
          "name": "#sudo-website",
          "url": "http://example.com/sudo-website/"
     }
    ]
}
</script>
~~~
So in the examples above, a domain at the root url would be type WebSIte.   A declaration of type WebPage (at some sub-directory level) would indicate a new distinct entity with a website like structure beneath this new "root".

The [folksonomy](https://en.wikipedia.org/wiki/Folksonomy) property could be used on both types, but are more common on these sudo-website hosts.

**Comment by akuckartz** [comment] 2020-01-11 08:02
@EnnexMB *Why* do you want to "designate the main pages of my websites as homepages" ?

**Comment by EnnexMB** [comment] 2020-01-11 10:17
For the same reason that I would designate the About page as type "WebPage > AboutPage", the Contact page as type "WebPage > ContactPage", etc.

**Comment by WeaverStever** [comment] 2020-01-11 14:50
@EnnexMB 
So what happens when you have dozens of ContactPages and AboutPages on a domain?  Do you think that just because you've created a subtype of HomePage that Google is going to understand why your domain has so many contact pages?

At best, Google will create an instance of ContactPage and the last one it reads will be the contact page data for your domain. Alternately, it is possible that your domain will just end up getting sandboxed.

There is 30 years of programming based upon one root page per domain, the root page is currently designated as WebSite in the schema.  Yes the way some people host entities (in subdirectories) has changed over the last decade, but just adding subtype of homePage will not address this non-trivial change you are asking for.

**Comment by danbri** [comment] 2020-01-11 14:57
Didn't I politely close this issue? the point wasn't to have it reemerge
the next day under a different name...

**Comment by WeaverStever** [comment] 2020-01-11 14:58
Please close

**Comment by EnnexMB** [comment] 2020-01-11 15:25
@danbri , would you please answer the question above, whether @WeaverStever is correct that FOAF:HomePage would NOT provide the functionality of structured data?

**Comment by danbri** [comment] 2020-01-11 16:05
foaf:homepage (lowecase) expresses a realtionship between something, and
something else, which holds whenever that second thing is the homepage of
the first thing.

It seems this conversation is full of confusion relating to whether
foaf:homepage is used within the page being described. That situation is
possible but not required.

If you use it in sensible rdfa or json-ld markup Google could in theory
extract it using our usual mechanisms; however currently we don't, and I
doubt we will. I only mentioned it as a solution for people who want to
express things around homepageyness for their own purposes (analytics,
local search systems, or whatever...).

**Comment by EnnexMB** [comment] 2020-01-11 18:54
If Google doesn't look at foaf, then I don't think I have any use for it. I don't need structured data for my own analytics. My understanding of the purpose of structured data is to help bots understand my content. So it appears that foaf is not a solution for that.

I agree with closing this issue. I opened it to ask a question that was hanging from the previous thread, which was whether `foaf:homepage` is a suitable substitute for the nonexistent `WebPage > HomePage`. The answer is apparently no.

I don't understand why in the world the folks who make decisions on what to include in the schema think that Web developers ought to be able to designate which [`WebPage`](https://schema.org/WebPage)s are `AboutPage`s, `ContactPage`s, `FAQPage`s, and even `RealEstateListing`s, but not `HomePage`s. It doesn't seem that that is about to change any time soon, and further discussion about it here does seem to be pointless.

**Comment by WeaverStever** [comment] 2020-01-11 19:06
@EnnexMB 

Because the contactPage and aboutPage generally belong to the domain / website on a one to one basis -- homePage would have similar properties.

RIght now WebSIte == HomePage
If you insist on hosting multiple sites -- This passes SDTT
~~~
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "url": "http://example.com/",
  "about": [
    {
      "@type": "WebSite",
      "url": "http://example.com/psuedo-website-1/",
      "name": "psuedo-website-1",
      "about": [
        {
          "@type": "AboutPage",
          "url": "http://example.com/psuedo-website-1/about.html"
        },
        {
          "@type": "ContactPage",
          "url": "http://example.com/psuedo-website-1/contact.html"
        }
      ]
    },
    {
      "@type": "WebSite",
      "url": "http://example.com/psuedo-website-2/",
      "name": "psuedo-website-2",
      "about": [
        {
          "@type": "AboutPage",
          "url": "http://example.com/psuedo-website-2/about.html"
        },
        {
          "@type": "ContactPage",
          "url": "http://example.com/psuedo-website-2/contact.html"
        }, 
        {
          "@type": "WebPage",
          "url": "http://example.com/psuedo-website-2/mywebpage.html"
        }
      ]
    }
  ]
}
</script>
~~~

The above might tell the SDTT that the collection of webpages belong to that sub-website. you would probably have to reproduce the same script in the head of every page.

Go ahead and try it, let us know how it works out

**Comment by jvandriel** [comment] 2020-01-11 19:11
> "I don't understand why in the world the folks who make decisions on what to include in the schema think that Web developers ought to be able to designate which WebPages are AboutPages, ContactPages, FAQPages, and even RealEstateListings, but not HomePages. It doesn't seem that that is about to change any time soon, and further discussion about it here does seem to be pointless."

Occasionally something gets added to the vocabulary because a consumer of such data expresses the 'need' for such data. For example, Google had a use for FAQPage and thus it was added to the vocabulary (after a request was made).

What you might not be aware of is that there is a large part of schema.org that was created before it was launched (eg, subtypes of LocalBusiness but also most subtypes of WebPage, and others). In hindsight many of these types didn't add anything 'useful' to the vocabulary as no consumer of such data has risen (yet).

Now one might therefore suggest we clean up the vocabulary and remove those types nobody seems to use for but the problem with that is that we aren't always aware which types are used. Reason being to some things might be used for different purposes other than helping search engines understand the content on a page (or any other type of resource being described). For example, I tend to use WebPage and its subtypes for Analytical purposes and therefor publish them, yet without expecting the search engines to ever do anything with that data. And therefor removing things like WebPage (and its subtypes), could have unforeseen negative consequences.

So the fact unfortunately is that schema.org contains quite a few things that don't get used much nor are maintained by the community, mostly due to decisions that were made before it was made accessible to the rest of the world.

**Comment by EnnexMB** [comment] 2020-01-11 19:38
Oh boy! So now I find out that the existence of subtype `AboutPage` is not an argument for creating subtype `HomePage` because `AboutPage` is just as useless as `HomePage` would be because Google ignores it.

This raises a whole new question. If I'm going to implement structured data in my websites, how do I do that in a way that doesn't waste time and structure with types and subtypes that are going to be ignored? The [specs for `Webpage`](https://schema.org/WebPage) list its subtypes, but is there a way to find out which types and subtypes actually have an affect on how Google and other bots understand my pages? I don't want to just "decorate" my HTML, as WeaverStever put it before.

**Comment by WeaverStever** [comment] 2020-01-11 19:56
Bots do not understand anything, they process data.  Decorating your pages gives the bot a context or category so that it can narrow the semantic definition of how you are using a word or phrase.

If you are selling guitars, then the word "bridge" probably does not mean a river-crossing or dental work. 

You are decorating your page with interesting nuggets and ornaments that match data consumer's search history. (aka search relevance)

**Comment by jvandriel** [comment] 2020-01-11 20:03
> _"would be because Google ignores it."_

So far it seems there's not a single application using such data, not just Google.

> _"If I'm going to implement structured data in my websites, how do I do that in a way that doesn't waste time and structure with types and subtypes that are going to be ignored?"_

If you just want to add markup for those things that are officially supported, than you'll have to look at the documents provided by search engines themselves:
- [Bing](https://www.bing.com/webmaster/help/marking-up-your-site-with-structured-data-3a93e731)
- [Google](https://developers.google.com/search/docs/data-types/article)
- [Yandex](https://yandex.com/support/webmaster/schema-org/what-is-schema-org.html) 
- (Anybody know if Yahoo still has a resource?)

And of course there are others that consume schema.org markup (eg [Pinterest](https://developers.pinterest.com/docs/rich-pins/overview/)).

It's up to each consumer of schema.org data to decide what the requirements for their applications are. Schema.org itself doesn't 'tell' consuming applications what they should use.

**Comment by danbri** [comment] 2020-01-12 17:12
Thanks, Jarno!

For Google, the Search Gallery at
https://developers.google.com/search/docs/guides/search-gallery is the best
entry point!

We do make some less visible use of other schemas but sticking to markup
with more tangible benefits is a general good rule for most...

**Comment by WeaverStever** [comment] 2020-01-13 18:53
@jvandriel 

I read some time ago that Bing and Yahoo are the same back-end.

**Comment by jeannieh** [comment] 2020-01-13 19:01
https://yandex.com/support/webmaster/scYhema-org/what-is-schema-org.html
<https://yandex.com/support/webmaster/schema-org/what-is-schema-org.html>

**Comment by jeannieh** [comment] 2020-01-15 09:48
https://yandex.com/support/webmaster/schema-org/what-is-schema-org.html

**Comment by danbri** [comment] 2020-01-27 17:00
I think this conversation has fizzled out. Thanks all.

**Closed by danbri** 2020-01-27 17:00 UTC
