### ISSUE TITLE
Place.elevation

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#2796] opened 2021-01-05 17:05 UTC
How come https://schema.org/elevation doesn't apply to Place?

**Comment by ThomasThelen** [comment] 2021-02-01 17:13
You can say that your Place has GeoCoordinates with `geo`. From there, you can attach the elevation. This is of course problematic if your Place doesn't exist in real life. As for _why_ elevation is defined on a GeoCoordinates object and _not_ Place? I'd say that it probably has to do with the need for specifying elevation relative to _something_. ie what's elevation 0? https://en.wikipedia.org/wiki/World_Geodetic_System gives the framework for talking about elevation. In order to work in that framework, you need lat/long points-hence the attachment of the property onto GeoShape and GeoCoordinates since they have lat/long. A Place _also_ has a latitude and longitude, so I also can't see the reason why elevation isn't applicable there.

Example of using it with GeoCoordinates:
```
{
  "@context": "https://schema.org",
  "@type": "Place",
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": "40.75",
    "longitude": "73.98",
    "elevation": "200"
  },
  "name": "Empire State Building"
}
```

**Comment by VladimirAlexiev** [comment] 2021-02-01 17:50
Elevation 0 is sea level

**Comment by dr-shorthair** [comment] 2021-02-01 19:15
EPSG:5100 - though note that it specifically says that location and time are required. It is actually a bit vague.

**Comment by VladimirAlexiev** [comment] 2021-02-02 15:13
To point out the obvious: we're not discussing the definition of Elevation, just why it's applied to GeoCoordinates but not to Place.

**Comment by philbarker** [comment] 2021-02-02 17:47
I guess it's not applied to Place directly because (a) it's not quite as important to as many people as long. and lat. are, and (b) looking at the example of Empire State Building as a place, it leads to questions like do you mean elevation of the ground at that point or the top of the building that is there. 

Definition is relevant though, and that is provided by `GeoCoordinates`, as mentioned above.

**Comment by VladimirAlexiev** [comment] 2021-02-03 09:13
@philbarker You seem to argue that a Place is not GeoCoordinates. Well then, I'll argue that a Building is not a Place. The place of Empire State is obviously at ground level. Don't confuse Elevation with Height.

Please explain how your rationalization justifies that I can't attach elevation to Matterhorn.

**Comment by vholland** [comment] 2021-02-03 14:59
My recollection is that when this was originally discussed, we considered adding the property to Place, but got bogged down in the definition. What is the elevation of Canada? Is it the mean elevation? The elevation of the mid point? The elevation of Ottawa?

Rather than get bogged down, we used GeoCoordinates because that seemed localized enough to avoid confusion. If there is a desire to express elevations of more expansive places, we should take that up.

**Comment by ThomasThelen** [comment] 2021-02-03 18:22
@vholland it sounds like the issue is lack of resolving power in the `elevation` property. Without a term for `meanElevation`, or `midpointElevation`, there's no way of knowing what the modeler semantically means (it's too general). The same way we can't talk about a `mountainBike` if the only term available is `Bike`.

To me, those examples  are only valid if there's a way of specifying a collection of lat/long points that make up a bounding box (something we can average over or take the midpoint of). The motivation for this idea is the following, `What is the latitude and longitude of Canada?`
It's a trick question because Canada is an aggregation of lat/long points. We don't have a way to treat Canada as a single point on a map, which means it's nonsensical to ask about its lat/long (do we mean the midpoint across the country? The lat/long of its biggest sea port?, etc). If there were a way to talk about _all_ of the points, then we can start taking about average elevation, midpoint elevation, etc.

Under this framework, lat/long should be removed from Place and if a modeler wants to talk about latitude, longitude, and elevation they should be using an associated `GeoCoordinates` or `GeoShape`. This is explicitly handled in `GeoShape` by specifying its related [circle](https://schema.org/circle). In doing so, the modeler has the flexibility of assigning the latitude and longitude where they find appropriate - bounding the elevation to the single point. Another argument for removing it from Place is that it's redundant with GeoCoordinates. What happens when a Place has a lat/long specified and _also_ has a GeoCoordinates specified but with conflicting coordinates? Are users forced to duplicate information between these classes?

Looking at the definition of [Ottawa](https://www.wikidata.org/wiki/Q576209), we can see that the folks over at Wiki Data did _not_ include a latitude and longitude for this type. We can also see the same for [Canada](https://www.wikidata.org/wiki/Q16).

At the end of the day, life is full of compromises. If `Place` is going to stay broken with latitude and longitude, I would argue that it should also have an elevation to keep parity with the definition of 'elevation' _and_ because I see no difference in a machine readable 'localization' between a  `GeoCoordinates` and a `Place`. That discretion seems to be left to the modeler.

**Comment by VladimirAlexiev** [comment] 2021-02-05 01:20
@ThomasThelen look better:
![Screenshot_20210205-031348_Chrome.jpg](https://user-images.githubusercontent.com/536250/106975991-4362c580-6760-11eb-9974-566ad05c4506.jpg)
(And BTW this is not that Ottawa).

Of course we need to bring elevation together with lat,long.

A good proportion of places are spot features, and attaching a plain POINT geo coordinates for that case is a bit redundant. And you can never break the  millions of already existing schema:Place .

Oh, were just wasting time here. My guess is this issue will sit unresolved for a couple of years, then be closed automatically.

**Comment by ThomasThelen** [comment] 2021-02-05 07:51
@VladimirAlexiev Ah my mistake! I somehow missed the big map and coordinates. [Here's](https://www.wikidata.org/wiki/Q619845) an example that supports the idea of having the elevation with the latitude and longitude (taking back the claim about lat/long I made about wikidata above). It's a type of [geographic location](https://www.wikidata.org/wiki/Q2221906) where the three properties are shown together. That might be useful in convincing someone that schema:elevation belongs on schema:Place (in addition to your points above).

> Oh, were just wasting time here. My guess is this issue will sit unresolved for a couple of years, then be closed automatically.

It looks like people make pull requests with their suggestions fairly often, and this being a community effort I don't see any reason preventing someone who cares enough to make one of their own.

**Closed** 2024-10-12 02:32 UTC
Labels: no-issue-activity
