### ISSUE TITLE
itemOffered as microdata and JSON-LD

### ISSUE THREAD

**Issue by e-orlov** [schemaorg/schemaorg#1002] opened 2016-02-22 13:04 UTC
On validating construction like Event→AggregateRating as Microdata Testing Tool doesn't fire an error on missing itemReviewed. But on validating same construction as JSON-LD it does.

**Comment by danbri** [comment] 2016-02-22 14:15
Hi @e-orlov. This is the issue tracker for the schema.org project itself, which does not currently operate any kind of testing tool. Are you talking about Google's tool at https://developers.google.com/structured-data/testing-tool/ or some other? It is best to report the problem to whoever is behind the tool. While it is useful to hear of these issues, we can't monitor all schema.org tools within this project so I'll close the issue now. We can still exchange comments here regardless of whether the issue is open, btw.

**Closed by danbri** 2016-02-22 14:15 UTC

**Comment by e-orlov** [comment] 2016-02-25 10:21
Hi Dan!
While the Google's Structured Data Testing Tool is the only reliable tool, which makes a Schema.org's markup validation, so if i (and many other) test some markup with it, and there rises an error, so the cause of error could be on the both sides: on the tool side and on the Schema.org's side. The tool could just validate wrong, Schema.org could contain some logical break. I mean, if tools fires a validation error, you never know, it because of the tool, or because of Schema.org broken logic.

**Comment by jaygray0919** [comment] 2016-02-25 14:26
+1 for @e-orlov

We've raised similar issues generated by Google Structured Data Testing Tool (GSDTT) only to be told that a test structure is a valid schema.org structure. But if GSDTT fires an error, who is wrong: the user (me), GSDTT or the schema.org data model?

From our point of view, TRUTH is GSDTT. We may model a data structure according to the schema.org model, but if GSDTT fires an error, then - operationally - the structure is wrong. We have to fix the structure to be GSDTT valid, even at the cost of lost re-usability.

As a fallback, we also use Structured Data Linter (SDL). Unlike GSDTT, which understandably only validates schema.org, SDL will validate the logical structure of other ontologies (RDF, etc.). We see that some structure using schema.org grammar are valid on SDL but invalid on GSDTT. In those cases we accept SDL as TRUTH. (as an aside, SDL will fire errors that are not errors on GSDTT. We usually update the structure to conform to both SDL and GSDTT).

IOHO, there needs to be a thread between logic errors discussed here and the folks responsible for GSDTT.

/jay
