### ISSUE TITLE
Offer is broken on the website

### ISSUE THREAD

**Issue by dunglas** [schemaorg/schemaorg#2012] opened 2018-07-16 08:58 UTC
It looks like specific properties of `Offer` aren't displayed on the website: https://schema.org/Offer
For instance `price` is not listed.

**Comment by dbs** [comment] 2018-07-16 09:51
I see `price` listed at https://schema.org/Offer in Firefox and Chrome. Perhaps your cache has stored a temporarily broken version? Maybe try a different browser or loading it again in a private / incognito window.

**Comment by dbs** [comment] 2018-07-17 07:42
So maybe this is region-specific behaviour on the part of AppEngine then? Because I'm still seeing `price` in `Offer` here in Germany.

**Comment by Dataliberate** [comment] 2018-07-17 08:12
I am working on this at the moment with the intention of laying this issue
to rest, hopefully in the next release.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment] 2018-07-25 23:21
@RichardWallis is there a better issue tracking this? It has cropped up several times, but only needs tracking in one place. The problem isn't offer specific and I know you're investigating so I'll close this issue.

**Closed by danbri** 2018-07-25 23:21 UTC
