### ISSUE TITLE
Excepted type of "upvoteCount" and "downvoteCount"

### ISSUE THREAD

**Issue by PendalF89** [schemaorg/schemaorg#601] opened 2015-06-15 13:43 UTC
Hello!
I have comments with "Likes" and "Likes" count shows as "+5", "-3", "0" etc. Can i use this format ("+5", "-3") for "upvoteCount" and "downvoteCount" properties?

**Comment by vholland** [comment] 2015-06-15 19:30
You may want to look at issue #137. The UserInteraction model is being updated in the next release.

**Comment by vholland** [comment] 2015-09-15 19:27
Duplicate of issue #137.

**Closed by vholland** 2015-09-15 19:27 UTC
