### ISSUE TITLE
Feature: Product Schema => Volume [ Vitamin D Milk 1gal ]

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#544] opened 2015-05-26 08:17 UTC
Many products are sold by volume. Lotions, Perfumes, Liquid Consumables, etc. We need to be able to express product volume.

**Comment by mfhepp** [comment] 2015-05-26 13:45
This is readily supported via 

a) http://schema.org/includesObject ->  http://schema.org/TypeAndQuantityNode (with this you can specify exactly how much of an item is included in an offer) 

b) http://schema.org/priceSpecification -> http://schema.org/UnitPriceSpecification -> http://schema.org/eligibleQuantity -> http://schema.org/QuantitativeValue for indicating the validity of a price by non-overlapping quantities.

If you want to model quantity discounts, simply attach two UnitPriceSpecification entities to the offer with differing prices and non-overlapping quantities for eligibleQuantity.

There are many examples given at http://wiki.goodrelations-vocabulary.org/Cookbook/Pricing.

You only have to replace the GoodRelations identifiers by the ones in schema.org, as listed here:

http://wiki.goodrelations-vocabulary.org/Cookbook/Schema.org#Naming_Differences

**Comment by inetbiz** [comment] 2015-05-26 16:31
@mfhepp thanks for that. But, if product schema is going to have Height, Width, Depth, Weight. There is no reason not to include volume.

**Comment by mfhepp** [comment] 2015-05-26 18:56
Ah, I understand. You want a volume property for product.

As of now, you can immediately use additionalProperty with a suitable UN/CEFACT code for indicating the volume of a liquid.

I hesitate to add schema:volume to schema:Product, because 

1. this is a property that applies only to small part of all products (not to electronics, cars, books, etc.) and
2. as long as search engines only need to display that value (but not use it for computations), schema:additionalProperty will serve as well.

Without any data at hand, I would argue that only a minority of products sold in Web shops are liquid.

If we go that route, I would rather propose a schema:productQuantity property with a range of schema:QuantitativeValue. This could then be used for arbitrary units of measurement.

It would also be a nice addition to the existing mechanism for quantities in GoodRelations, because in the current model, you can only specify the amount of an object contained in the offer. But for boxed products, it may indeed make sense to indicate the quantity contained in the boxed product.

@danbri @vholland - what do you think about schema:productQuantity or schema:containedQuantity property for schema:Product? We could also wait for a GS1 extension, which might provide this detail. Practically, schema:additionalProperty should do the trick for search engines for the moment.

**Comment by DDeering** [comment] 2015-05-26 19:08
+1 to the idea of adding schema:productQuantity property to Product.  
Good idea.

David

**Comment by Aaranged** [comment] 2015-05-26 19:32
FWIW I think "volume" is pretty broadly applicable and, like weight/width/depth/height is a universal measurement container (i.e. the unit employed is not prescribed, as per any property that takes a QuantitativeValue).

In the product realm I think this actually applies to a huge number of products:  shampoo, perfume, toothpaste, alcohol, etc., etc.  It's also applicable to non-liquid products whose capacity is provided as a volume measurement, such as luggage or packaging.

And I think having this available as a property is also forward-thinking, insofar as it can be used for other schemas.  Let's say, for example, it was considered desirable to create an item type for recipeIngredient (like, um, RecipeIngredient) because right now the ingredient, ingredient quantity, and measure used that ingredient quantity are all different.  AFAIK there are only three ways of expressing the measurement for an ingredient:  simple item count (3 bananas), weight and volume:  we're good-to-go with count and weight, just not volume (and we haven't shied away from using 12 different measurement unit properties, like transFatContent, to support NutritionInformation).

Just an example leaning on extensibility, but it illustrates again just how fundamental the concept of "volume" is.  I don't think we should be afraid of adding it to core, and so force webmasters to use something more complicated.

At first blush something like schema:productQuantity looks promising to me, but I'd not that volume itself isn't an arbitrary unit of measurement, but a higher-level concept (and more applicable, for now, than other measurement types one might encounter, like "energy").

**Comment by jvandriel** [comment] 2015-05-26 20:01
I've had a quick look at GS1's specification documentation (http://www.gs1.org/docs/idkeys/gtin/GS1_Standard_Specification_Document_GTIN_OTW_Vocabulary.pdf) and from that I gather they resolve this by specifying:

```
gs1:TradeItem (see also http://schema.org/Product)
    > gs1:netContent 
        > gs1:MeasurementType
            > gs1:measurementUnitCode (see also http://schema.org/unitCode)
                > string
            > gs1:measurementValue (see also http://schema.org/value)
                float
```

Which I guess in schema.org would be:

```
schema:Product
    > schema:additionalProperty
        > schema:PropertyValue
            > schema:unitCode
                > schema:URL/Text
            > schema:value
                > schema:StructuredValue/Boolean/Text/Number
```

And by comparing the two I'd say that adding a schema.org equivalent for gs1:netContent seems a reasonable request, especially with the idea in mind that GS1 is showing interest in a gs1.schema.org extension.

**Comment by vholland** [comment] 2015-05-27 15:00
FWIW, I prefer a new `productQuantity` property on `Product` that takes a `QuantitativeValue` over using `additionalProperty`.

**Comment by mfhepp** [comment] 2015-05-27 16:09
I would also prefer a "productQuantity" property over a "volume" property. The former could hold volume, weight, number of items information . And this will really make sense, because the original GoodRelations lacked the notion of packaging units (*).

"Volume" can mean lots of different things, and in the case of boxed quantities of liquids, the quantity of liquid is likely not the volume of the shape.

For the records, I am also not perfectly happy with the weight, length, ... properties, for several reasons. They could mean the packaging size or weight or the product size / weight. Just to counter the use of these as a justification.


(*) To be precise: I assumed at that time that such properties would come from external product ontologies, like my OWL variant of eClass, eClassOWL. Historically, GoodRelations was designed to be just (a) the meta-model for product ontologies and (b) the domain model for commercial aspects of product information. If you have time and want to understand those underlying assumptions, the GoodRelations Technical Report is still available at

    http://www.heppnetz.de/projects/goodrelations/GoodRelations-TR-final.pdf



-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by Aaranged** [comment] 2015-05-27 17:34
If we go with productQuantity + QuantitativeValue - which I still think is crazy onerous for webmasters wanting to state basic measurements - we need to do a better job with the documentation and examples.

Right now schema.org/QuantitativeValue (and QualitativeValue) aspires to read like stereo instructions, but don't actually provide instructions.  Are there any examples that feature either of these anywhere on schema.org.

**Comment by RLRichardson** [comment] 2015-05-27 17:46
From my perspective, you are all talking about a lot of different things as if it were the same....
Dimensions - Height, Width, Depth
Volume (cube) - In most instances = H x W x Depth
Quantity - a simple item count (Aaron's 3 bananas)
and finally, 
Content
Net content is a "legal" requirement in most retail selling situations, and is also a recursive attribute, in that if you look at most products, you'll see something like "net content 19.9 Fl Oz, 1Pt, 0.9 Fl Oz, 500 ML

**Comment by RLRichardson** [comment] 2015-05-27 17:47
From my perspective, you are all talking about a lot of different things as if it were the same....
Dimensions - Height, Width, Depth
Volume (cube) - In most instances = H x W x Depth
Quantity - a simple item count (Aaron's 3 bananas)
and finally,
Content
Net content is a "legal" requirement in most retail selling situations, and is also a recursive attribute, in that if you look at most products, you'll see something like "net content 16.9 Fl Oz, or 1Pt, 0.9 Fl Oz, or 500 ML

**Comment by mfhepp** [comment] 2015-05-27 18:42
I think that @inetbiz meant "net content" for boxed liquid products when proposing  a "volume" property. and no geometric volume. A property with a range of QuantitativeValue can handle very different types of values - dimensions, quantities (which are not limited to item counts - 7.3 meters of rope are a quantity in my understanding)., volumes, etc.

This is why a productQuantity + QuantitativeValue approach is attractive - with one property we can allow expressing various types of "product quantity" information.

**Comment by vholland** [comment] 2015-05-27 19:29
@mfhepp +1

I knit and it is useless to know the shipping dimensions of yarn. The amount is usually expressed in weight or better yet, quantity as expressed in yards/meters.

I'd rather not have a property for each of physical dimensions, liquid volume, dry volume (e.g. pecks), total length, etc.

**Comment by inetbiz** [comment] 2015-05-27 20:01
@mfhepp probably so? A perfume bottled boxed could be 3" tall, 1.5" wide with a depth of 1.8" and weight xxx. Its net volume of perfume is 1.5ml.

Either way, I agree with @Aaranged and not make it so difficult to implement.

**Comment by chaals** [comment] 2015-05-28 09:48
+1 to making this simple enough for normal people.

Net weight, dry weight, content volume, number of items - and some other measures - are important for describing offers in e.g. online supermarkets where a certain number of people shop through necessity, as well as many more for convenience.

For example if I buy a can of sardines or mussels - enough for one or two people to have on toast for breakfast, or to make a few hors d'oeuvres - I will know the net weight as a legal requirement, but also the number of items in the can, as a range - 6-8, or 20-28, or something, as important information to understand what I am getting.

These values are different from "shipping information" - total package size and weight (where volume is only rarely noted, and usually in container-loads…) - which is also important for calculating costs.

Note also the ambiguity of volume with audio volume, in thinking about what to call this.

**Comment by mfhepp** [comment] 2015-05-28 10:03
I think that adding a "netContent" or "productQuantity" property with a range of QuantitativeValue and a few good examples should do the trick.

If there is agreement, I can create a pull request for this.

Note that additional context can be provided via schema:valueReference, schema:name (attached to the schema:QuantitativeValue), or schema:additionalProperty (attached to the schema:QuantitativeValue).

**Comment by mfhepp** [comment] 2015-05-28 10:07
@chaals as for multiple units for the content (e.g. 10 slices , 128 g), you could simply use netContent twice.

We should vote on the naming, in particular about whether it should include a "net" prefix (which will be more intuitive for many use-cases and consistent with the GS1 definition), or prefer a broader "productContent", "packageContent" notion, deferring the indication of net vs. gross to schema:name, schema:additionalProperty, or schema:valueReference.

I prefer netContent but can also live with packageContent.

**Comment by inetbiz** [comment] 2015-06-18 10:59
Like @Aaranged said and @chaals commented. Please do not turn the methodology to describe volume into several more lines of code for webmasters to attempt to figure out. It will lead to LESS usage of schema.org. You already have 99% of all open source e-commerce NOT using schema.org at all.

**Comment by mfhepp** [comment] 2015-06-18 11:52
@inetbiz 

First: We have ca. 20 - 30 % schema.org markup adoption among top-ranked e-commerce sites, as a recent sample of mine has shown. These are arguably the bigger sites and adoption on the long tail is typically slower - as with many new Web technologies that are inherently complex and non.trivial to master for a smaller organization.

Second, if you are unable to parse such information into two proper QuantitativeValue nodes, you can always use a raw string as a fall-back mechanism.

Third, we always have to balance simplicity for simple cases with compatibility with advanced cases, Many of the shortcuts and simplifications proposed are only slightly simpler, but rule out a clean approach for more complex cases.

The beauty of using schema:QuantitativeValue is that it provides a clean way to

- model point values and open and closed intervals
- supports units of measurements, i.e. the property is not bound to a single unit
- allows value references

while making markup only insignificantly more complex.

**Comment by inetbiz** [comment] 2015-06-18 13:38
I'll watch for any changes to schema.org/QuantitativeValue (and QualitativeValue) and propose changes in open source. Thanks for the reply, @mfhepp ;)

**Comment by vholland** [comment] 2015-08-17 13:15
@mfhepp Are you working on this? The issue came up again in issue #738 . 

To resolve this can we add "volume" and some of the other properties @chaals listed along with netContent?

**Comment by mfhepp** [comment] 2015-08-17 14:46
I will take care ;)

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by danbri** [comment] 2015-09-23 15:14
Aside (as this was the most relevant existing issue I can find), see also http://qudt.org/vocab/unit/units-space-and-time.html for a very detailed treatment of units of measure.

**Comment by leaandsandeman** [comment] 2017-02-02 14:07
We indeed just wanted a simple answer to this question which led us to this convoluted post about something which is standard requirement when selling liquids (certainly in the EU). We sell wine and would like to declare the unit size as some sort of internationally recognised volume attribute in our markup. Unfortunately wine volume is traditionally declared in centilitres and litres e.g. 37.5cl, 75cl, 1.5l, but the UN/CEFACT codes do not include centilitres as a UOM.

We are going to stick with the additionalProperty solution originally suggested by mfhepp, but the schema configuration needs to be made a LOT clearer for humans e.g. better examples of different scenarios and not requiring users to bounce between Google, Schema.org, Goodrelations etc... to figure out configurations for common templates e.g. brand pages with listed products; there's no definitive schema example anywhere to be found, yet this is a template found on most ecommerce websites?

That said, we appreciate it's a difficult task to create and curate a master taxonomy, but the general guidelines could be much clearer with examples from top ranked e-commerce web pages perhaps?
 Thanks for all the hard work!

**Comment by RichardWallis** [comment] 2017-02-02 19:43
@leaandsandeman Maybe sharing the results of your efforts in a way that it could be added as examples would be helpful to others.

**Closed** 2024-11-24 02:47 UTC
Labels: schema.org vocab, no-issue-activity
