### ISSUE TITLE
main git repository is proprietary

### ISSUE THREAD

**Issue by npettiaux** [schemaorg/schemaorg#3216] opened 2022-11-20 14:33 UTC
Dear all,

I discover this important community that I want to join. But I see with some major troubles that the main git server is github that belongs to Microsoft and is the subject of a legal action (against Github & Microsoft) by a major US legal firm related to the fact that Copilot has been trained with free and open-source software and its results are distributed without taking care neither to the licences nor to the CGU. 

I consider therefore that it is a major threat to the whole project and its community to remain on a server that is maintained by a proprietary company, furthermore one of the GAFAM.

I have cloned the repository to https://codeberg.org/npettiaux/schemaorg and I hope many other people have done it too.

I consider that as long as the main git repository is on github, or any service managed by a private company whose main objective is to make profit not to improve mankind, this is a blocking problem.

I hope that sooner than later you can move to a server hosted by a non profit company or an administration. 

The recent twitter car shows the clearly the risks coming with a dependance on a private actor.

Best regards,

NIcolas Pettiaux

**Comment by danbri** [comment] 2022-11-20 16:22
Hello Nicolas,

Thank you for sharing your concern. I disagree.

Before we moved to git, and to github, we used a Mercurial repository hosted at W3C (a membership Consortium of many organizations including “proprietary companies”). Like many other organizations, the community at W3C decided back in 2014 that the best way to engage effectively with a broad developer community was to migrate to Github.com and to the Git protocol and software.

As explained in our [old repo](https://dvcs.w3.org/hg/webschema/summary), kindly still hosted read-only by W3C,” W3C now makes extensive (and effective) use of Github in a growing set of [repositories](https://github.com/w3c).

Although Schema.org is not a project of W3C’s, we have taken the same path here, with some success. The move was disruptive, and for less technical folk interested in Schema.org, introduced regrettable difficulties as various things need relearning, plus broken/dangling URLs etc.

I do not plan to move our main repository again without a very serious reason (eg. El*n-Twitter levels of collapse), since to do so is disruptive of our work and our collaborations, many of which (eg [json-ld](https://github.com/json-ld/json-ld.org), [Dublin Core](https://github.com/dcmi), [IPTC](https://github.com/iptc), [datacommons.org](https://github.com/datacommonsorg), [Wikidata](https://github.com/Wikidata), [Biohackathon](https://github.com/elixir-europe/biohackathon-europe-2022), [Solid](https://github.com/solid/) /cc @RubenVerborgh …and others) continue to use Github. If these communities leave, it will be a sign we should revisit this matter.

I am sure Codeberg is interesting, but I fear you massively underestimate the disruption a move would cause. It is also unusual to make such radical proposals to a project which you have little history of contributing to. 

Regarding your clone of this repo, it is a natural part of Git, Github and opensource practice to clone, copy, fork etc. (so long as licenses and terms are respected). However, as you have created an offsite copy of our project’s main repository, I ask that you please be careful to clarify that your repo and fork have no special standing or official status within the Schema.org project.

Regarding CoPilot, we should not set a precedent of assuming all legal actions are appropriate/fair and deserve to succeed. Regardless or whether (your words) they are from 
“by a major US legal firm” or not. As a project Schema.org has always had a good relationship with Microsoft, and would not have been successful without their support. 

Regarding any concern that our Schema definitions might end up in a large language model: frankly, that would be interesting but harmless. We should remember that Schema.org markup is on many many millions of websites. Moving those all to Codeberg is not a solution to anything.

My unsolicited advice, if you are overly concerned about large companies supporting open standards, is to focus on building opensource tools that actually consume RDF data - whether in Schema.org or other RDFS vocabularies. RDF data is hard to consume at scale, especially given its powerful expressivity. Looking at how (ethically trained, open licensed) LLMs can integrate with RDF / Knowledge Graph data would be a useful thing to do. And if your problem is with capitalism itself, the issue is beyond the scope of this repo.

Schema.org is designed to bring such technologies into mainstream use, within the context of the world as it is. This requires a focus on using data to solve real people’s real problems (finding jobs, educational opportunities, a recipe for dinner, or a fact check of political talking points). Moving our repo to a new and unknown site would be counterproductive to such goals.

Since this issue is not going to be implemented, I will close it for now (but leave it open for other comments).

**Closed by danbri** 2022-11-20 16:22 UTC

**Comment by npettiaux** [comment] 2022-11-20 16:38
Much thanks Mr @danbri for your precise and long answer. I do understand indeed that a move might be a strong disruption and cause many problems for many people. This is definitively not an event I would like to see. 

I will set clearly the wording you propose on codeberg. 

I understand that Microsoft is a very large corporation with very diverse interests and that some people in some parts play nicely the collective game of standard definition, as a corporation, I see also that it does not bring forward the culture of openness I would very much like to see. Microsoft is a company that much to often is not kind to people (not to say they lie), they do not actively enough play fairly the set of open standards (their definition of OOXML is not compatible as far as I know with ODT) and their actions on the desktops to keep the users and prevent them from installing other browsers is mainly drafted in lies. 

It is also true that such a proposal is inadequate as I have not worked on the project not contributed for a long time, but it reflects the concern we are some to have.

I do also consider that Google plays the very same bad games as Microsoft, and neither play fairly for an open decentralized internet based only on open standards as far as I see. 

One of the only good recent news is that as of the end of last week both companies have been officially banned from every school in France, opening the field for free and open source software as much as possible.

Best regards,

**Comment by danbri** [comment] 2022-11-20 17:30
Thanks for understanding our perspective.

For what it is worth, as someone who has worked on progressing RDF since before Google was even incorporated, … my perspective is that these large companies are very often not helpfully conceptualized as agents or people. They are the aggregate outcome of 10s or 100s of people’s efforts, perspectives, actions and inactions. I now work for Google and am happy of the opportunity it gives me and many colleagues to do useful things that would otherwise be impossible. RDF touches millions more ordinary people’s lives, in positive ways, than it did in the 13 years before Google adopted and prompted it via Schema.org. 

This isn’t the place to evaluate balance sheets for which parties in this world are good actors. I hope the free and open source software community make the most of the situation in France, and that other Git-based services flourish, just in case Elon Musk buys Github some day.

**Comment by npettiaux** [comment] 2022-11-20 17:37
Much thanks again. What I find sad is that Google and Microsoft, these very large institutions, are not playing as nice actors in the internet. Both must contribute to it for their own sake, but both want to enclose enveryone in their own « ecosystems ».  And too often, their shown behavior as seen from the outside, for usual people, is that they claim to be good actors, but much too often their true actions are to enclose people, not to free them.
Perhaps could we devise a mechanism for automatic copies of the schemaorg hierarchies of data in such a way that people who want to contribute and not touch github in any way (as it is sadly enough, badly used by Microsoft as a Trojan horse with their developpement IDE VSCode that, even as open source as it is, does contain trackers that are bad, can do so. 
Best regards

**Comment by danbri** [comment] 2022-11-20 21:07
As I say, the best way to contribute is to build things that use RDF data, such as the millions of pages that contain Schema.org in JSON-LD, Microdata etc.

Our github here is using a Microsoft platform. The schema.org site is opensource code running on Google AppEngine. If these are not things you are comfortable with, there is a mailing list at W3C, or you might try tagging #schemaorg on a purity-oriented platform like Mastodon, if you have feedback on the schemas based on building things for people using data expressed in them. That said, I am afraid it sounds like you are looking for levels of perceived “purity” such that we will always disappoint you, and your energies may fit in better elsewhere. 

To belabour the point - I also edit most of these Schemas on a proprietary osx laptop, using CPU and GPU that are not open hardware. I do so sitting in a country where I benefit from centuries of imperialism and which points deadly nuclear weapons at innocent web users in other countries. And that’s without getting into the working conditions of the people that made my computers (or yours), clothes, or issue-tracking platform.  But we all do what we can. You might feel about the makers of VS Code the way some feel about [the author of Emacs](https://www.thedailybeast.com/famed-mit-computer-scientist-richard-stallman-defends-epstein-victims-were-entirely-willing) but in a web standards setting we always look for common ground. This is not the place to debate whether Schema.org collaborators can use VS Code, any more than it is the place to ask whether Stallman software should be allowed in French schools.
