### ISSUE TITLE
True/False are both  instances *and* subclasses of Boolean

### ISSUE THREAD

**Issue by sesuncedu** [schemaorg/schemaorg#226] opened 2015-01-16 02:35 UTC

**Comment by danbri** [comment] 2015-01-21 10:41
For reference,

        danbri-macbookpro:data danbri$ rdfa schema.rdfa | grep '/True'
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Boolean> .
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#label> "True" .
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#comment> "The boolean value true" .
        <http://schema.org/True> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
        danbri-macbookpro:data danbri$ rdfa schema.rdfa | grep '/False'
        <http://schema.org/False> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Boolean> .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#label> "False" .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#comment> "The boolean value false" .

@rvguha  - is there some deep reason for this, or it something got lost in translation somewhere?

**Comment by danbri** [comment] 2015-01-21 12:18
Closing as duplicate of https://github.com/schemaorg/schemaorg/issues/130

**Closed by danbri** 2015-01-21 12:18 UTC
Labels: needs review
