### ISSUE TITLE
http://www.schema.org should return a 301 redirect to http://schema.org

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#521] opened 2015-05-21 06:24 UTC
Currently, the schema.org main page and type/property/individual pages are served from both the naked domain AND from the www.schema.org hostname, which can lead to a proliferation of wrong class / property URLs in markup.

Instead of silently serving the content from both URLs, there should be a proper 301 redirect to the canonical URL.

As said, the problem also exists for URLs for types and properties, e.g.
    http://www.schema.org/Thing

which is even more serious.

Also note that the current implementation does not support HTTP HEAD requests, which it should, IMO.

Evidence:

$ curl -i http://www.schema.org/
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Date: Thu, 21 May 2015 06:18:00 GMT
Server: Google Frontend
Content-Length: 4630
Alternate-Protocol: 80:quic,p=0

$ curl -i http://www.schema.org/Thing
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Date: Thu, 21 May 2015 06:21:07 GMT
Server: Google Frontend
Content-Length: 20554
Alternate-Protocol: 80:quic,p=0

$ curl -I http://schema.org
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: text/html; charset=UTF-8
Content-Length: 188
Date: Thu, 21 May 2015 06:23:06 GMT
Server: Google Frontend
Alternate-Protocol: 80:quic,p=0

**Comment by danbri** [comment] 2015-05-22 09:06
For redirects this is a duplicate of #4, for HTTP HEAD, of #256. But thanks for the reminder!

**Closed by danbri** 2015-05-22 09:06 UTC
Labels: site tools + python code
