### ISSUE TITLE
Properties that are (required) not marked on schema.org website

### ISSUE THREAD

**Issue by ITZAP** [schemaorg/schemaorg#1177] opened 2016-05-22 02:41 UTC
All Google Developer Guides for rich snippet code markup specify which schema Properties are compulsory "**Required**" and those that are "**Recommended**".  See for example ...
[https://developers.google.com/search/docs/data-types/products#type_definitions](url)

However, the schema.org website does not state which Properties are (Required) anywhere. Please add that critical information to schema.org for the information of webmasters.

Thanks, Gary Flack, ITZAP Website Design Works.

**Comment by scor** [comment] 2016-05-22 02:56
Hi Gary,

Schema.org does not dictate what properties are be "required" or "recommended" by design. Those are too application-specific to be part of the high-level schema definitions found on schema.org. The required and recommended properties you are referring to are specifically required/recommended by Google for their product to work well, but another company offering a different product using schema.org may choose different properties to be required for their product. This comes down to separating schema.org from all the companies that are building products based on schema.org (examples are all the major search engines). At the end of the day, the more schema.org properties you decide to publish on your site, the better.

**Comment by ITZAP** [comment] 2016-05-22 03:36
Hmmm, yes I see, and I do appreciate your reply.  Many thanks @scor.  I did wonder who in fact was actually making the decisions about "required" properties ... and adding more requirements at fairly regular intervals.

For instance, schema markup for a basic Article or BlogPosting must now be (according to Google) a **full-on AMP Article**, **NewsArticle** or **BlogPosting** to pass muster through their Structured Data Testing Tool.  And that is **far more complex**.  So what was OK last month returns multiple Errors today.

Webmasters understand that schema.org will continue to evolve and requirements will change.  But the tendency I have observed is to drastically increase the complexity of markup, not to simplify anything.

if, as you say, Required and Recommended properties are to vary between companies offering search products, then the schema.org project looses consistency.

That being the case, then for Webmasters striving to remain compliant, these issues become a real headache.  And that is the feedback I would like to pass on to the schema.org project group here.

**Comment by danbri** [comment] 2016-05-22 21:58
Hi @ITZAP - @scor has already explained it. I appreciate your frustration, but much of that I would encourage you to direct at (my employer) Google rather than at schema.org! In particular "So what was OK last month returns multiple Errors today." is not a schema.org issue (e.g. via https://productforums.google.com/forum/#!categories/webmasters/structured-data ). As schema.org we do give some rough hints as to the kinds of description that may be useful, via our collection of examples, but they are only an indication. 

I'm going to close this issue as there is little we can do on this front directly, but thanks again for sharing your frustrations, we'll bear them in mind where possible.

**Closed by danbri** 2016-05-22 21:58 UTC
